spring.application.name=promotionmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/promotion_manager
spring.datasource.username=postgres
spring.datasource.password=Sindhuja4!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true